export const routes = {
  login: 'login',
  esqueci1: 'esqueci1',
  esqueci2: 'esqueci2',
  esqueci3: 'esqueci3',
  esqueci4: 'esqueci4',
  esqueci5: 'esqueci5',
  medicoLaudos: 'medicoLaudos',
  conversas: 'Conversas',
  notificacoes: 'notificacoes',
  menuPaciente: 'menuPaciente',
  preencherLaudos: 'preencherLaudos',
  configuracoes: 'configuracoes',
  perfil: 'perfil',
  seguranca: 'seguranca',
  alterarEmail: 'alterarEmail',
  alterarSenha: 'alterarSenha',
  suporte: 'suporte',
  faleConosco: 'faleConosco',
  horarios: 'horarios',
  termos: 'termos',
  adicionarFavoritos: 'adicionarFavoritos',
  favoritosConfig: 'favoritosConfig',
};
